---
- name: Create directories
  file:
   path: "{{ data_dir }}/octoprint/data"
   state: directory
   mode: 0755

- name: Run container
  docker_container:
    name: octoprint
    image: octoprint/octoprint:{{ octorpint_version }}
    volumes:
    - "{{ data_dir }}/octoprint/data:/octoprint/octoprint:rw"
    devices:
      - "/dev/ttyUSB0"
    restart_policy: unless-stopped
    network_mode: host
