---

- hosts: all
  roles:
    - name: common
      tags: common
    - name: docker
      tags: docker
    - name: users
      tags: users
    - name: tools
      tags: tools
    - name: node_exporter
      tags: node_exporter

- hosts: netbox
  roles:
    - name: dnsmasq
      tags: dnsmasq
    - name: openvpn_exporter
      tags: openvpn_exporter
    - name: plex
      tags: plex
    - name: octoprint
      tags: octoprint

- hosts: rpi01
  roles:
    - name: prometheus
      tags: prometheus
    - name: grafana
      tags: grafana
    - name: nginx_rpi
      tags: nginx_rpi
    - name: unifi_controller
      tags: unifi_controller
    - name: mosquitto
      tags: mosquitto
    - name: zigbee2mqtt
      tags: zigbee2mqtt
    - name: mqtt2prometheus
      tags: mqtt2prometheus
    - name: home_assistant
      tags: home_assistant
    - name: kiosk  #  works only for Raspberry Pi
      tags: kiosk
      vars:
        kiosk_url: http://localhost:{{ homeassistant_port }}
