---
- name: Create directories for openvpn_monitor
  file:
   path: "{{ data_dir }}/openvpn-monitor/conf"
   state: directory
   mode: 0755

- name: Copy openvpn-monitor config
  template:
    src: openvpn-monitor.conf
    dest: "{{ data_dir }}/openvpn-monitor/"
  notify: restart openvpn-monitor

- name: Run openvpn-monitor
  docker_container:
    name: openvpn-monitor
    image: ruimarinho/openvpn-monitor  # pharlan/docker-openvpn-monitor-arm  # rpi version
    volumes:
      - "{{ data_dir }}/openvpn-monitor/openvpn-monitor.conf:/openvpn-monitor/openvpn-monitor.conf"
    restart_policy: unless-stopped
    network_mode: host
