---
- name: create directories for containers
  file:
   path: "{{ item }}"
   state: directory
   mode: 0755
  with_items:
    - /srv/nginx/conf/html

- name: Copy nginx configs
  template:
    src: nginx.conf.j2
    dest: /srv/nginx/conf/nginx.conf
  notify: restart nginx

- name: Copy mime configs
  template:
    src: mime.types
    dest: /srv/nginx/conf/mime.types
  notify: restart nginx

- name: Copy Web page
  copy:
    src: page/
    dest: /srv/nginx/conf/html
  notify: restart nginx

- name: Copy cert
  copy:
    dest: "/etc/ssl/raspberrypi.home.crt"
    content: "{{ raspberrypi_home_crt }}"
    mode: 0744
  notify: restart nginx

- name: Copy key
  copy:
    dest: "/etc/ssl/raspberrypi.home.key"
    content: "{{ raspberrypi_home_key }}"
    mode: 0744
  notify: restart nginx

- name: Run nginx
  docker_container:
    name: nginx
    image: arm32v7/nginx:{{ nginx_version }}
    volumes:
      - "/srv/nginx/conf/html:/etc/nginx/html:ro"
      - "/srv/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/srv/nginx/conf/mime.types:/etc/nginx/mime.types:ro"
      - "/etc/ssl/:/etc/ssl:ro"
    restart_policy: unless-stopped
    network_mode: host
