alertmanager_port: 9093
dht22_port: 8001
dnsmasq_ui_port: 5380
grafana_port: 3000
homeassistant_port: 8123
mosquitto_exporter_port: 9234
mosquitto_port: 1883
mqtt2prometheus_port: 9001
mtproxy_port: 9876
node_exporter_port: 9100
octoprint_port: 8081
odinc_exporter_port: 9099
openvpn_exporter_port: 9176
plex_port: 32400
prometheus_port: 9090
