---
- name: Create directories for usb coordinator
  file:
   path: "{{ item }}"
   state: directory
   mode: 0755
  with_items:
    - "{{ data_dir }}/data/zigbee2mqtt"

- name: Run container for usb coordinator
  docker_container:
    name: zigbee2mqtt
    image: 'koenkk/zigbee2mqtt:{{ zigbee2mqtt_version }}'
    privileged: yes
    volumes:
      - "{{ data_dir }}/data/zigbee2mqtt/:/app/data:rw"
      - "/run/udev:/run/udev:ro"
    devices:
      - "/dev/ttyACM0"
    env:
      TZ: "{{ my_timezone }}"
    restart_policy: unless-stopped
    network_mode: host

- name: Create directories for lan coordinator
  file:
   path: "{{ data_dir }}/data/zigbee2mqtt_lan"
   state: directory
   mode: 0755

#- name: Copy config for lan coordinator
#  template:
#    src: zigbee2mqtt_lan.conf
#    dest: "{{ data_dir }}/data/zigbee2mqtt_lan/configuration.yaml"
#  notify: restart zigbee2mqtt

- name: Run container for lan coordinator
  docker_container:
    name: zigbee2mqtt_lan
    image: 'koenkk/zigbee2mqtt:{{ zigbee2mqtt_version }}'
    privileged: yes
    volumes:
      - "{{ data_dir }}/data/zigbee2mqtt_lan/:/app/data:rw"
    env:
      TZ: "{{ my_timezone }}"
    restart_policy: unless-stopped
    network_mode: host
