---
- name: Create directories for prometheus
  file:
   path: "{{ item }}"
   state: directory
   mode: 0755
  with_items:
    - "/srv/prometheus/conf"
    - "{{ data_dir }}/data/prometheus"

- name: Create symbolic link for data directory
  file:
    src: "{{ data_dir }}/data/prometheus"
    dest: "/srv/prometheus/data"
    state: link
    force: yes

- name: Copy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /srv/prometheus/conf/prometheus.yml
  notify: restart prometheus

- name: Run Prometheus
  docker_container:
    name: prometheus
    image: rycus86/prometheus
    volumes:
      - /srv/prometheus/conf/:/etc/prometheus/:ro
      - /srv/prometheus/data/:/prometheus:rw
    command:
        "--config.file=/etc/prometheus/prometheus.yml \
          --storage.tsdb.path=/prometheus \
          --storage.tsdb.retention=90d \
          --web.console.libraries=/usr/share/prometheus/console_libraries \
          --web.console.templates=/usr/share/prometheus/consoles \
          --web.external-url=http://0.0.0.0/prometheus/ \
          --web.route-prefix=/prometheus/"
          #              --storage.local.target-heap-size=268697600"
    restart_policy: unless-stopped
    network_mode: host
