---
- name: Create directories for Home Assistant
  file:
   path: "{{ item }}"
   state: directory
   mode: 0755
  with_items:
    - "{{ data_dir }}/data/hassio/conf"
    - "/srv/hassio/conf/www"

- name: Copy office floorplan
  copy:
    src: office.png
    dest: /srv/hassio/conf/www/office.png

- name: Copy NetworkMap module
  copy:
    src: zigbee2mqtt-networkmap.js
    dest: /srv/hassio/conf/www/zigbee2mqtt-networkmap.js

- name: Copy Lovelace
  template:
    src: "{{ item }}.j2"
    dest: "/srv/hassio/conf/{{ item }}"
  with_items:
    - ui-lovelace.yaml
  tags: [ "home-configs", "ui-lovelace" ]

- name: Copy Themes
  copy:
    src: files/themes
    dest: /srv/hassio/conf/themes
  tags: [ "home-configs", "ui-lovelace" ]

- name: Copy Home Assistant config
  template:
    src: "{{ item }}.j2"
    dest: "/srv/hassio/conf/{{ item }}"
  with_items:
    - configuration.yaml
    - sensors.yaml
    - automations.yaml
    - customize_glob.yaml
  notify: restart home-assistant
  tags: home-configs

# bug?
#wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
#sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb

- name: Run Home Assistant container
  docker_container:
    name: home-assistant
    image: homeassistant/home-assistant:{{ ha_version }}
    volumes:
      - /srv/hassio/conf:/config
    env:
      TZ: "{{ my_timezone }}"
    restart_policy: unless-stopped
    network_mode: host
